### ISSUE TITLE
agregar elemento a linkedlist

### ISSUE THREAD

**Issue by bcsaldias** [pvchaumier/IIC2133#1]
Hola !

Muchas gracias por el material !! Te pasaste.

Tengo  una pregunta, puede ser que el método de agregar un elemento a la linkedlist no esté funcionando bien con los punteros ?, principalmente el else del método list_add ! .. si compruebas que está ok feliz de que me avises porque tal vez yo estoy fallando en otra cosa.

Gracias !
Belén

**Comment by pvchaumier** [comment]
Super si te ayuda !

Todo puede ser ;) Pero no entiendo bien tu pregunta.. Que seria el problema con punteros ? Podrias darme un ejemplo de codigo porfa ?

**Comment by bcsaldias** [comment]
La verdad creo que es un error muy personal, xq el ejemplo me corre bien
pero al cambiarle el tipo de datos al "value " a uno por referencia (a una
estructura) en vez de a un int no se me redirecciona.

Lo volveré a revisar y te aviso, en una de esas era que estaba quedándome
dormida.

Saludos y gracias !

**Comment by pvchaumier** [comment]
Problema visto directamente. Issue closed.
